services:
  db_production:
    container_name: db-production-container
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: production
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5434:5432'
    volumes:
      - /workspaces/docker-volumes/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - "5050:80"
    depends_on:
      - db_production
    volumes:
      - /workspaces/docker-volumes/pgadmin:/var/lib/pgadmin
  krile:
    container_name: krile-container
    restart: unless-stopped
    environment:
      DB_NAME: production
      DB_HOST: db_production
      DB_PORT: 5432
    env_file:
      - .env
    depends_on:
      - db_production
    ports:
      - 5678:5678
      - 6066:6066
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db_production
