services:
  db_production:
    container_name: db-production-container
    image: postgres:15
    environment:
      POSTGRES_DB: production
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5434:5432'
    volumes:
      - /media/adata1/docker/volumes/db-production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5
  db_develop:
    container_name: db-develop-container
    image: postgres:15
    environment:
      POSTGRES_DB: develop
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5433:5432'
    volumes:
      - /media/adata1/docker/volumes/db-develop:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - "5050:80"
    depends_on:
      - db_production
      - db_develop
    volumes:
      - /media/adata1/docker/volumes/krile-pgadmin:/var/lib/pgadmin
  krile:
    container_name: krile-container
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${KRILE_TOKEN}
      DB_NAME: production
      DB_HOST: db_production
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ROLE_ADMIN: ${ROLE_ADMIN}
      ROLE_DEVELOPER: ${ROLE_DEVELOPER}
      WAIT_DEBUG: ${WAIT_DEBUG}
    depends_on:
      - db_production
    ports:
      - 5678:5678
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db_develop
      - db_production